### ISSUE TITLE
Cannot support .NET Framework 4.6.1

### ISSUE THREAD

**Issue by William-Y** [yigolden/OpenSlideNET#26]
Hi All,

I'm using .NET Framework 4.6.1 SDK.
Is there any version of the OpenSlideNET that support .NET Framework?
I will be appreciate if you can give me one.

Thanks a lot!

**Comment by MM-YJN** [comment]
OpenSlideNET targets .NET Standard 1.3. So it should be usable in .NET Framework 4.6.1 application. Just install the NuGet package from Visual Studio and it should be fine.

However, to make it functional, you have to make sure the native binaries of OpenSlide is installed on the target computer. (libopenslide-0.dll and its dependencies are next to your executable, or the directory containing them is in the PATH environment variable) Also, make your application targets either x86 or x64 (Not 'Any CPU'), matching your OpenSlide binaries.

Feel free to ask any questions if these instructions does not work for you.

**Comment by William-Y** [comment]
I was failed installing the NuGet package from VS. It seems doesn't work well with package OpenSlideNET.NativeStubs. 

And I download the Source Code of OpenSlideNET for generating .dll file but failed. VS said Interop\Interop.Utf8String.cs : line 19 struct should be a type.

Now I'm confused.

**Comment by MM-YJN** [comment]
What is the version of your VS? It should work with VS2017.

**Comment by William-Y** [comment]
I'm using VS2017 community

**Comment by MM-YJN** [comment]
Line 19 of Interop.Utf8String.cs is using the ref struct feature, which is supported only on recent versions of Rosyln compiler. It seems like your VS doesn’t recognize this syntax.

To build the DLL file, you have to use a version of VS that support C# 7.2 syntax with ‘.NET Core cross-platform development workload’ installed. Since you are using the DLL in Windows environment, you can safely remove the NativeStubs dependency from the project. You can change the targetframework property in csproj file to ‘net461’. However, to use the DLL in your project, you have to make sure the dependencies used by OpenSlide are also referenced in your project. (System.ValueTuple, System.Runtime.CompilerServices.Unsafe, System.Buffers, SixLabors.ImageSharp) I wouldn’t recommend this approach as it could potentially be a tedious work to manage these dependencies manually. (That’s why we use NuGet.)

Can you upgrade your VS using the Visual Studio Installer and make sure ‘.NET Core cross-platform development workload’ is also installed? And then try the NuGet package again?

If it is inconvenient for you to upgrade VS, can you please attach a screenshot of the About dialog of your VS showing versions of various components. I will try to investigate the problem of NuGet not working.

**Comment by William-Y** [comment]
Thanks so much! 
I've solved the problem by updating VS to the newest version and adding the DLL in my project. It's indeed the problem of my old C# version.
